### ISSUE TITLE
Can't apply a StartEvent connector template

### ISSUE THREAD

**Issue by johnBgood** [bpmn-io/element-templates-cli#18]
### Describe the Bug

As discussed [here](https://camunda.slack.com/archives/C057H178R9T/p1711557338310999), I have an issue applying the RabbitMq start event inbound connector to a StartEvent element (see attached file).

### Steps to Reproduce

1. Download and extract [Archive.zip](https://github.com/bpmn-io/element-templates-cli/files/14786623/Archive.zip)
2. You should have 2 files: **test.bpmn** and **template.json**
3. Run this command: `element-templates-cli --diagram test.bpmn --template template.json --element elementId --output result.bpmn`
4. This error occurs:

> failed to import <bpmn:StartEvent id="elementId" />
ReferenceError: document is not defined
    at create$1 (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:890:5)
    at Text.layoutText (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12243:20)
    at Text.getDimensions (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12236:15)
    at TextRenderer.getExternalLabelBounds (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12318:39)
    at BpmnImporter.addLabel (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12788:33)
    at BpmnImporter.add (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12758:10)
    at Object.element (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:9945:25)
    at visit (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:9666:20)
    at visitIfDi (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:9673:38)
    at handleFlowNode (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:9830:20)
unhandled error in event listener ReferenceError: document is not defined
    at create$1 (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:890:5)
    at Text.layoutText (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12243:20)
    at Text.getDimensions (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12236:15)
    at TextRenderer.getExternalLabelBounds (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12318:39)
    at UpdateLabelHandler.postExecute (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:23059:32)
    at CommandStack._internalExecute (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:20102:15)
    at CommandStack.execute (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:19959:8)
    at Modeling.updateLabel (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:23104:22)
    at file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:16298:14
    at invokeFunction (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:3592:13)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ReferenceError: document is not defined
    at create$1 (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:890:5)
    at Text.layoutText (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12243:20)
    at Text.getDimensions (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12236:15)
    at TextRenderer.getExternalLabelBounds (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:12318:39)
    at UpdateLabelHandler.postExecute (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:23059:32)
    at CommandStack._internalExecute (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:20102:15)
    at CommandStack.execute (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:19959:8)
    at Modeling.updateLabel (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:23104:22)
    at file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:16298:14
    at invokeFunction (file:///Users/jonathanroques/.nvm/versions/node/v21.6.2/lib/node_modules/element-templates-cli/dist/index.js:3592:13)

Node.js v21.6.2

### Expected Behavior

The template is correctly applied and a **result.bpmn** file is created.

### Environment

- Host (Browser/Node version), if applicable: Node v21.6.2
- OS: MasOS 14.4.1
- Library version: element-templates-cli@0.3.0

**Comment by barmac** [comment]
Hi, I am able to reproduce the error. Thank you for creating the issue. What I found is that if you remove the element label (property name), the template is applied correctly. So it is probably a problem within https://github.com/bpmn-io/bpmn-js-headless which still relies on browser API to render external labels. I will create an issue in the repo and link this one.

**Comment by barmac** [comment]
Requires https://github.com/bpmn-io/bpmn-js-headless/issues/2 to be fixed.
